### PR TITLE
Fix deprecated library use and add a basic INSTALL.txt for Ubuntu

### PR DESCRIPTION
**Pull request by davidstrauss**

### CODE REVIEW

**Comment by antong** [comment]
Thank you for caring about this and giving this some attention! I will integrate these changes but will need to fix the hashlib compatibility issue. For the set() changes I'd prefer to squash them into a single commit. I can do that for you. OK with you?

**Comment by antong** [comment]
I did the fixup I think was needed and pushed the result to my proposed updates branch 'pu' at antong/ldaptor@8b040149758cfe978040. Are my changes OK with you? If so, I'll merge to master.

Thanks
Anton

**Comment by davidstrauss** [comment]
The changes to maintain 2.4 compatibility look good to me.

**Comment by antong** [comment]
OK, applied to master. Thanks!

**Pull request closed without merging**
