### PR TITLE
* is valid in an ldapfilter's value field for substring matching

### PR DESCRIPTION
**Pull request by mkomitee**
Currently, the literal "_" character is disallowed in the value field of an ldapfilter. The '_' character is a valid character to facilitate substring matching in ldap searches, and so should be allowed.

### CODE REVIEW

**Comment by antong** [comment]
I think the valid uses for the asterisk character are handled by the "substring" and "present" syntax elements (search for those in the file). Could you give an example of a valid filter string that is not correctly handled before your change and that is correctly handled after your change? Just so I understand what the change does.

Thanks!
Anton

**Comment by mkomitee** [comment]
-- that does imply that my current supplied patch is probably not appropriate.

**Comment by antong** [comment]
Testing by running the module as a script gives:

```
$ python -m ldaptor.ldapfilter "(cn=*)"
LDAPFilter_present(value='cn')

$ python -m ldaptor.ldapfilter "(cn=foo*)"
LDAPFilter_substrings(type='cn', substrings=([LDAPFilter_substrings_initial(value='foo')], {}))

$ python -m ldaptor.ldapfilter "(cn=*bar)"
LDAPFilter_substrings(type='cn', substrings=([LDAPFilter_substrings_final(value='bar')], {}))

$ python -m ldaptor.ldapfilter "(cn=foo*bar)"
LDAPFilter_substrings(type='cn', substrings=([LDAPFilter_substrings_initial(value='foo'), LDAPFilter_substrings_final(value='bar')], {}))

$ python -m ldaptor.ldapfilter "(cn=*a*b*c*)"
LDAPFilter_substrings(type='cn', substrings=([LDAPFilter_substrings_any(value='a'), LDAPFilter_substrings_any(value='b'), LDAPFilter_substrings_any(value='c')], {}))
```

So it seems at least these filters are parsed as intended. What is the original problem?

Thanks!
Anton

**Comment by mkomitee** [comment]
So it does seem to be generating the correct thing to do searches. Apparently our ldap administrator created a custom map which mimics NIS Netgroups for which the key on which we search ends in a literal `*` which isn't matched by the wildcard `*`. In all of our other code we escape the `*` with a `\` in our search filters. I'm not 100% sure this is valid as per the RFC, but it works in openldap and the ldapsearch command line tools which ship with redhat. Similarly, it's possible with the python ldap module in the standard library. 

It has the literal `*` because we simply used the output of `revnetgroup`  (http://www.unix.com/man-page/FreeBSD/8/revnetgroup/) which has they key for the map be `fqdn.*`. 

I understand the need to parse the ldap search filter when using ldaptor to power an ldap server, but is it really necessary to do so in the client libraries? 

Perhaps a better way to go about this than my submitted patch would be to allow `\*` in the filter, and not consider it a substring. Unfortunately, I'm not proficient with pyparsing enough to know how to pull that off.

**Comment by antong** [comment]
Escaping in RFC2254 is by backslash always followed by two hexdigits. So for a literal "*", use "\2a". I'm closing this pull request now as it turned out it is not the right change. Feel free however to open an issue if you find a bug, or ask questions on the Twisted mailing list.

Thanks for caring about Ldaptor!
Anton

**Comment by mkomitee** [comment]
Just as an FYI, that doesn't appear to work either, but as you're right that
this is not the right change, there's no need to reopen the request.

**Pull request closed without merging**
